sonar.exclusions=static/css/**/*.css,static/plugins/**/*,static/js/src/vendor/**/*,static/js/dist/**/*,templates/**/*.html

# Ignore legacy maintainability code smells that require risky refactoring
sonar.issue.ignore.multicriteria=e1,e2,e3,e4,e5,e6,e7,e8
sonar.issue.ignore.multicriteria.e1.ruleKey=javascript:S3504
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e2.ruleKey=go:S3776
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.go
sonar.issue.ignore.multicriteria.e3.ruleKey=go:S1192
sonar.issue.ignore.multicriteria.e3.resourceKey=**/*.go
sonar.issue.ignore.multicriteria.e4.ruleKey=go:S1191
sonar.issue.ignore.multicriteria.e4.resourceKey=**/*.go
sonar.issue.ignore.multicriteria.e5.ruleKey=go:S1135
sonar.issue.ignore.multicriteria.e5.resourceKey=**/*.go
sonar.issue.ignore.multicriteria.e6.ruleKey=go:S101
sonar.issue.ignore.multicriteria.e6.resourceKey=**/*.go
sonar.issue.ignore.multicriteria.e7.ruleKey=javascript:S1135
sonar.issue.ignore.multicriteria.e7.resourceKey=**/*.js
sonar.issue.ignore.multicriteria.e8.ruleKey=javascript:S1479
sonar.issue.ignore.multicriteria.e8.resourceKey=**/*.js
